services:
  - type: web
    name: ctf-academia-ciber
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CTF_SECRET
        generateValue: true
